#!/usr/bin/env python3
"""Translate Polish Quarto survey-analysis reports to English."""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from translations_pass2 import PASS2
from translations_pass2_r3 import PASS2_R3
from translations_fixup import FIXUPS

ROOT = Path(__file__).resolve().parent.parent

FILES = {
    "sprawo1.qmd": "report1.qmd",
    "sprawozdanie2.qmd": "report2.qmd",
    "sprawozdanie3.qmd": "report3.qmd",
}

# Shared replacements (longest strings first when applied)
COMMON: list[tuple[str, str]] = [
    ("Analiza Danych Ankietowych", "Survey Data Analysis"),
    ("Sprawozdanie", "Report"),
    ("lang: pl", "lang: en"),
    ("p-wartość", "p-value"),
    ("P-wartość", "P-value"),
    ("p-wartości", "p-values"),
    ("Wnioski:", "Conclusions:"),
    ("Wniosek.", "Conclusion."),
    ("Wniosek.", "Conclusion."),
    ("**Wniosek.**", "**Conclusion.**"),
    ("**Wnioski:**", "**Conclusions:**"),
    ("**Wyniki.**", "**Results.**"),
    ("**Wyniki**", "**Results**"),
    ("**Analiza:**", "**Analysis:**"),
    ("**Interpretacja.**", "**Interpretation.**"),
    ("**Komentarz.**", "**Comment.**"),
    ("Część I", "Part I"),
    ("Część II", "Part II"),
    ("Część III", "Part III"),
    ("Zadanie", "Task"),
    ("Wprowadzenie", "Introduction"),
    ("Podsumowanie", "Summary"),
    ("Zadania dodatkowe", "Additional tasks"),
    ("Przedział ufności", "Confidence interval"),
    ("Przedziały ufności", "Confidence intervals"),
    ("Liczebność", "Count"),
    ("Liczba", "Count"),
    ("Kategoria", "Category"),
    ("Statystyka", "Statistic"),
    ("Hipoteza", "Hypothesis"),
    ("Decyzja", "Decision"),
    ("Wniosek", "Conclusion"),
    ("Płeć", "Gender"),
    ("Staż pracy", "Tenure"),
    ("Staż", "Tenure"),
    ("Kobieta", "Female"),
    ("Mężczyzna", "Male"),
    ("kierownicy", "managers"),
    ("Kierownik", "Manager"),
    ("Nie kierownik", "Non-manager"),
    ("nie kierownik", "non-manager"),
    ("Poniżej 1 roku", "Less than 1 year"),
    ("1-3 lata", "1-3 years"),
    ("Powyżej 3 lat", ">3 years"),
    ("<1 rok", "<1 year"),
    (">3 lata", ">3 years"),
    ("do 35", "up to 35"),
    ("powyżej 55", "over 55"),
    ("Do 35 lat", "Up to 35"),
    ("36-45 lat", "36-45"),
    ("46-55 lat", "46-55"),
    ("Pow. 55 lat", "Over 55"),
    ("Zdec. nie zgadzam", "Strongly disagree"),
    ("Nie zgadzam", "Disagree"),
    ("Nie mam zdania", "No opinion"),
    ("Zgadzam", "Agree"),
    ("Zdec. zgadzam", "Strongly agree"),
    ("bardzo niezad.", "very dissat."),
    ("niezad.", "dissat."),
    ("bez zdania", "no opinion"),
    ("zad.", "sat."),
    ("bardzo zad.", "very sat."),
    ("zdec. nie", "str. disagree"),
    ("nie zg.", "disagree"),
    ("zgadzam", "agree"),
    ("zdec. tak", "str. agree"),
    ("brak podstaw do odrzucenia", "insufficient evidence to reject"),
    ("brak podstaw", "insufficient evidence"),
    ("nie mamy podstaw do odrzucenia", "we do not reject"),
    ("Odrzucamy H0", "Reject H0"),
    ("Brak podstaw do odrzucenia H0", "Insufficient evidence to reject H0"),
    ("Biblioteki", "Libraries"),
    ("Wczytanie danych", "Loading data"),
    ("Etykiety", "Labels"),
    ("Suma", "Total"),
    ("Negatywna", "Negative"),
    ("Pozytywna", "Positive"),
    ("Lek A", "Drug A"),
    ("Lek B", "Drug B"),
    ("Okres 1", "Period 1"),
    ("Okres 2", "Period 2"),
    ("Cała grupa", "Overall group"),
    ("Leczenie A", "Treatment A"),
    ("Leczenie B", "Treatment B"),
    ("Metoda", "Method"),
    ("Grupa", "Group"),
    ("Wymiar", "Dimension"),
    ("inercja", "inertia"),
    ("Prawdopodobieństwo", "Probability"),
    ("Postać", "Form"),
    ("Interpretacja", "Interpretation"),
    ("Model", "Model"),
    ("Wariant", "Variant"),
    ("Test", "Test"),
    ("chi-kwadrat", "chi-square"),
    ("iloraz wiarogodności", "likelihood ratio"),
    ("Palący", "Smokers"),
    ("Niepalący", "Non-smokers"),
    ("rak płuc", "lung cancer"),
    ("choroba serca", "heart disease"),
    ("choroba niedokrwienna", "coronary heart disease"),
    ("Analiza korespondencji", "Correspondence analysis"),
    ("wiersze", "rows"),
    ("kolumny", "columns"),
    ("staż 1", "tenure 1"),
    ("staż 2", "tenure 2"),
    ("staż 3", "tenure 3"),
    ("niezależne", "independent"),
    ("niezależna", "independent"),
    ("Zakres WIEK:", "WIEK range:"),
    ("Zmienna", "Variable"),
    ("Liczba braków", "Missing count"),
    ("Kategoria wiekowa", "Age category"),
    ("Udzial proc.", "Percent share"),
    ("Licznosc", "Count"),
    ("Tablica liczności", "Frequency table"),
    ("Profil kolumnowy", "Column profile"),
    ("Liczebności", "Counts"),
    ("Dolna Granica", "Lower bound"),
    ("Górna Granica", "Upper bound"),
    ("Okres", "Period"),
    ("Przed modyfikacją", "Before modification"),
    ("Po modyfikacji", "After modification"),
    ("Pokrycie", "Coverage"),
    ("Szerokość", "Width"),
    ("Metoda", "Method"),
    ("Dokładny (binom.test)", "Exact (binom.test)"),
    ("Asymptotyczny (prop.test)", "Asymptotic (prop.test)"),
    ("Moc – test dokładny", "Power – exact test"),
    ("Moc – test asymptotyczny", "Power – asymptotic test"),
    ("Różnica (asymp. − dokł.)", "Difference (asymp. − exact)"),
    ("Prawdziwe prawdopodobieństwo sukcesu (p)", "True success probability (p)"),
    ("Moc testu (P odrzucenia H₀)", "Test power (P(reject H₀))"),
    ("Krzywe mocy testu", "Power curves"),
    ("Prawdopodobieństwo pokrycia", "Coverage probability"),
    ("Średnia szerokość przedziału ufności", "Mean confidence interval width"),
    ("Nominalne 95 procent", "Nominal 95 percent"),
    ("Podsumowanie wyników weryfikacji hipotez", "Summary of hypothesis test results"),
    ("Satysfakcja", "Satisfaction"),
    ("Kierownictwo a płeć", "Management role and gender"),
    ("Satysfakcja a płeć", "Satisfaction and gender"),
    ("Praca w HR a płeć", "HR employment and gender"),
    ("Odsetek kobiet = 0.5", "Proportion of women = 0.5"),
    ("Poprawa A", "Improvement A"),
    ("Poprawa B", "Improvement B"),
    ("% popr. A", "% impr. A"),
    ("% popr. B", "% impr. B"),
    ("Z chorobami współist.", "With comorbidities"),
    ("Bez chorób współist.", "Without comorbidities"),
    ("Odsetek poprawy", "Improvement rate"),
    ("sigma (wart.osobl.)", "sigma (singular value)"),
    ("% wyjaśnionej", "% explained"),
    ("Wartości osobliwe i inercje z CA.", "Singular values and inertia from CA."),
    ("Dane z treści zadania", "Data from the task statement"),
    ("Kategoria odpowiedzi", "Response category"),
    ("Opis Tabeli", "Table description"),
    ("Opis Rysunku", "Figure description"),
    ("Opis Tabel", "Tables description"),
    ("Dane (odsetki zgonów rocznie):", "Data (annual death rates):"),
    ("Choroba", "Disease"),
    ("Trzy miary związku", "Three association measures"),
    ("Siła związku.", "Strength of association."),
    ("Rozważane pary:", "Pairs considered:"),
    ("Ilustracja numeryczna:", "Numerical illustration:"),
    ("Ryzyko przypisane", "Attributable risk"),
    ("Przykłady", "Examples"),
    ("niezależne", "independent"),
    ("zależność nieliniowa", "nonlinear dependence"),
    ("Konwencja 0 log 0 = 0", "Convention 0 log 0 = 0"),
    ("opcjonalnie p-wartość Monte Carlo", "optional Monte Carlo p-value"),
    ("Kodowania porządkowe", "Ordinal encodings"),
    ("Zastosowanie do pary", "Application to the pair"),
    ("Dokładny (symulowany", "Exact (simulated"),
    ("test symetrii", "symmetry test"),
    ("test symetrii.", "symmetry test."),
    ("Problem z zerami.", "Zero-count problem."),
    ("Idea.", "Idea."),
    ("Wyznaczanie poziomu krytycznego.", "Determining the critical level."),
    ("Wyniki i wnioski", "Results and conclusions"),
    ("Komentarz do wykresu.", "Comment on the figure."),
    ("\\usepackage{polski}", ""),
    ("\\usepackage{polyglossia}", ""),
    ("\\setdefaultlanguage{polish}", ""),
    ("\\usepackage[utf8]{inputenc}", ""),
    ("\\usepackage[T1]{fontenc}", ""),
]

REPORT1: list[tuple[str, str]] = [
    ('title: "Analiza Danych Ankietowych -- Sprawozdanie 1"',
     'title: "Survey Data Analysis -- Report 1"'),
    ("# Wstęp", "# Introduction"),
    ("# Część I -- analiza opisowa", "# Part I -- descriptive analysis"),
    ("## Zadanie 1 -- Wczytanie i przygotowanie danych",
     "## Task 1 -- Loading and preparing data"),
    ("### Weryfikacja braków danych", "### Checking for missing data"),
    ("## Zadanie 2 -- Kategoryzacja zmiennej wiekowej",
     "## Task 2 -- Categorizing the age variable"),
    ("## Zadanie 3 -- Analiza struktury respondentów (tablice liczności)",
     "## Task 3 -- Respondent structure (frequency tables)"),
    ("### Podział organizacyjny i staż pracy",
     "### Organizational breakdown and tenure"),
    ("### Płeć, stanowisko kierownicze i wiek",
     "### Gender, management role, and age"),
    ("# Zadanie 4 -- Rozkłady odpowiedzi na pytania ankietowe",
     "# Task 4 -- Response distributions for survey questions"),
    ("## Pytanie 1: Zadowolenie z dostępności materiałów szkoleniowych",
     "## Question 1: Satisfaction with availability of training materials"),
    ("## Pytanie 2: Szkolenia a możliwości awansu i potrzeby rozwojowe",
     "## Question 2: Training, promotion opportunities, and development needs"),
    ("# Zadanie 5 -- Tablice wielodzielcze (krzyżowe)",
     "# Task 5 -- Cross-tabulations"),
    ("## Analiza względem cech organizacyjnych",
     "## Analysis by organizational characteristics"),
    ("### Pytanie 1 a dział", "### Question 1 by department"),
    ("### Pytanie 1 a staż pracy", "### Question 1 by tenure"),
    ("### Pytanie 1 a stanowisko kierownicze", "### Question 1 by management role"),
    ("## Pytanie 1 a płeć", "## Question 1 by gender"),
    ("## Przygotowanie zmiennych CZY_ZADOW i CZY_ZADOW_2",
     "## Preparing variables CZY_ZADOW and CZY_ZADOW_2"),
    ("# Część II -- Estymacja przedziałowa", "# Part II -- interval estimation"),
    ("## Zadanie 2 -- Funkcja dla przedziału Cloppera-Pearsona",
     "## Task 2 -- Clopper-Pearson confidence interval function"),
    ("## Zadanie 3 -- Realizacje przedziałów ufności",
     "## Task 3 -- Confidence interval calculations"),
    ("## Zadanie 4 -- Symulacje prawdopodobieństwa pokrycia i długości",
     "## Task 4 -- Coverage probability and length simulations"),
    ("# Część III -- Weryfikacja hipotez statystycznych",
     "# Part III -- statistical hypothesis testing"),
    ("## Zadanie 5 -- Weryfikacja wybranych hipotez",
     "## Task 5 -- Testing selected hypotheses"),
    ("## Zadanie 6 -- Weryfikacja mocy testu (Symulacja Monte Carlo)",
     "## Task 6 -- Test power verification (Monte Carlo simulation)"),
    ("# Helper: zwraca surowy LaTeX tabeli bez żadnych floatów.",
     "# Helper: returns raw table LaTeX without floats."),
    ("# Używa \\captionof zamiast caption= żeby uniknąć konfliktu KOMA-script w minipage.",
     "# Uses \\captionof instead of caption= to avoid KOMA-script minipage conflicts."),
    ("# Helper: usuwa float table z surowego LaTeX kable (niezbędne przed minipage)",
     "# Helper: strips float table from raw kable LaTeX (needed before minipage)"),
    ("# Helper: drukuje dwie tabele obok siebie w minipage",
     "# Helper: prints two tables side by side in minipage"),
    ('labs(title = title, x = NULL, y = "Odsetek", fill = NULL)',
     'labs(title = title, x = NULL, y = "Percentage", fill = NULL)'),
    ('labs(title = "PYT_1 – Udział procentowy (kołowy)"',
     'labs(title = "PYT_1 – Percentage share (pie)"'),
    ('labs(title = "PYT_1 – Rozkład opinii (słupkowy)"',
     'labs(title = "PYT_1 – Opinion distribution (bar)"'),
    ('labs(title = "PYT_2 – Udział procentowy (kołowy)"',
     'labs(title = "PYT_2 – Percentage share (pie)"'),
    ('labs(title = "PYT_2 – Rozkład opinii (słupkowy)"',
     'labs(title = "PYT_2 – Opinion distribution (bar)"'),
    ('labs(title = "PYT_1 – Rozkład opinii (słupkowy)", x = NULL, y = "Odsetek (%)"',
     'labs(title = "PYT_1 – Opinion distribution (bar)", x = NULL, y = "Percentage (%)"'),
    ('labs(title = "PYT_2 – Rozkład opinii (słupkowy)", x = NULL, y = "Odsetek (%)"',
     'labs(title = "PYT_2 – Opinion distribution (bar)", x = NULL, y = "Percentage (%)"'),
    ('make_tab_licznosci(CZY_KIER, "Stanowisko kierownicze")',
     'make_tab_licznosci(CZY_KIER, "Management role")'),
    ('make_tab_licznosci(PLEC, "Płeć (PLEC)")',
     'make_tab_licznosci(PLEC, "Gender (PLEC)")'),
    ('make_tab_licznosci(DZIAL, "Dział (DZIAL)")',
     'make_tab_licznosci(DZIAL, "Department (DZIAL)")'),
    ('make_tab_licznosci(STAZ, "Staż pracy (STAZ)")',
     'make_tab_licznosci(STAZ, "Tenure (STAZ)")'),
    ('make_cross("DZIAL", "Dział")', 'make_cross("DZIAL", "Department")'),
    ('make_cross("STAZ", "Staż pracy")', 'make_cross("STAZ", "Tenure")'),
    ('make_cross("CZY_KIER", "Stanowisko kierownicze")', 'make_cross("CZY_KIER", "Management role")'),
    ('make_cross("PLEC", "Płeć")', 'make_cross("PLEC", "Gender")'),
    ('caption  = "Liczba brakow danych dla kazdej zmiennej"',
     'caption  = "Number of missing values for each variable"'),
    ('caption  = "Tablica liczności -- Kategoria wiekowa (WIEK\\_KAT)"',
     'caption  = "Frequency table -- Age category (WIEK\\_KAT)"'),
    ('caption = "Przedziały ufności Cloppera-Pearsona (95 proc.)"',
     'caption = "Clopper-Pearson confidence intervals (95%)"'),
    ('Okres = c("Przed modyfikacją (CZY_ZADOW)", "Po modyfikacji (CZY_ZADOW_2)")',
     'Okres = c("Before modification (CZY_ZADOW)", "After modification (CZY_ZADOW_2)")'),
    ("# Okres 1", "# Period 1"),
    ("# Okres 2", "# Period 2"),
    ("# Wyliczanie pokrycia", "# Computing coverage"),
    ("# Średnie długości przedziałów", "# Mean interval lengths"),
    ("B <- 5000 # liczba replikacji Monte Carlo", "B <- 5000 # number of Monte Carlo replications"),
    ("# brzegowe przypadki – unikanie błędów numerycznych", "# edge cases – avoid numerical errors"),
    ("# 1. Prawdopodobieństwo, że w firmie pracuje kobieta wynosi 0.5.",
     "# 1. Probability that an employee in the company is a woman is 0.5."),
    ("# 2. Prawdopodbieństwo, że pracownik uważa szkolenia za przystosowane",
     "# 2. Probability that an employee considers training adapted"),
    ("# do swoich potrzeb w 1. okresie jest większe bądź równe 0.7.",
     "# to their needs in period 1 is greater than or equal to 0.7."),
    ("# Zwykle testujemy H0: p >= 0.7 przeciw H1: p < 0.7.",
     "# We typically test H0: p >= 0.7 vs H1: p < 0.7."),
    ("# 3. Prawdopodobieństwo, że kobieta pracuje na stanowisku kierowniczym",
     "# 3. Probability that a woman holds a management position"),
    ("# jest równe prawdopodobieństwu, że mężczyzna pracuje na stanowisku kierowniczym.",
     "# equals the probability that a man holds a management position."),
    ("# 4. Prawdopodobieństwo, że kobieta uważa szkolenia za przystosowane",
     "# 4. Probability that a woman considers training adapted"),
    ("# w 1. okresie jest równe prawdopodobieństwu u mężczyzn.",
     "# in period 1 equals the probability among men."),
    ("# 5. Prawdopodobieństwo, że kobieta pracuje w HR jest >=",
     "# 5. Probability that a woman works in HR is >="),
    ("# prawdopodobieństwu, że mężczyzna pracuje w HR.",
     "# the probability that a man works in HR."),
    ('"5. Praca w HR a płeć (<=)"', '"5. HR employment and gender (<=)"'),
    ('ifelse(test1$p.value < 0.05, "Odrzucamy H0", "Brak podstaw do odrzucenia H0")',
     'ifelse(test1$p.value < 0.05, "Reject H0", "Insufficient evidence to reject H0")'),
    ('ifelse(test2$p.value < 0.05, "Odrzucamy H0 (p<0.7)", "Brak podstaw do odrz. H0 (p>=0.7)")',
     'ifelse(test2$p.value < 0.05, "Reject H0 (p<0.7)", "Insufficient evidence (p>=0.7)")'),
    ('ifelse(test3$p.value < 0.05, "Odrzucamy H0", "Brak podstaw do odrzucenia H0")',
     'ifelse(test3$p.value < 0.05, "Reject H0", "Insufficient evidence to reject H0")'),
    ('ifelse(test4$p.value < 0.05, "Odrzucamy H0", "Brak podstaw do odrzucenia H0")',
     'ifelse(test4$p.value < 0.05, "Reject H0", "Insufficient evidence to reject H0")'),
    ('ifelse(test5$p.value < 0.05, "Odrzucamy H0 (p_K<p_M)", "Brak podstaw do odrz. H0")',
     'ifelse(test5$p.value < 0.05, "Reject H0 (p_K<p_M)", "Insufficient evidence")'),
    ('caption = "Porównanie mocy testów przy p = 0.8 (Monte Carlo, B = 5000)"',
     'caption = "Comparison of test power at p = 0.8 (Monte Carlo, B = 5000)"'),
    ("Dodatkowo prezentujemy tabelę porównawczą mocy obu testów dla wybranej wartości alternatywnej $p = 0.8$ (odchylenie o 10 p.p. od $H_0$):",
     "We also present a comparison table of the power of both tests for the alternative value $p = 0.8$ (a 10 p.p. deviation from $H_0$):"),
    ("# Test dokładny (Clopper-Pearson / binom.test)",
     "# Exact test (Clopper-Pearson / binom.test)"),
    ("**Wnioski z symulacji Monte Carlo:**", "**Conclusions from the Monte Carlo simulation:**"),
    ("**Wnioski z symulacji:**", "**Conclusions from the simulation:**"),
    ("**Wnioski z testowania hipotez:**", "**Conclusions from hypothesis testing:**"),
]

REPORT2: list[tuple[str, str]] = [
    ('title: "Analiza Danych Ankietowych — Sprawozdanie 2"',
     'title: "Survey Data Analysis — Report 2"'),
    ("## Zadanie 1 — Przedział ufności dla wektora prawdopodobieństw",
     "## Task 1 — Confidence interval for a probability vector"),
    ("## Zadanie 2 — Funkcja p-wartości w testach $\\chi^2$ dla $H_0: p = p_0$",
     "## Task 2 — p-value function in $\\chi^2$ tests for $H_0: p = p_0$"),
    ("## Zadanie 3 — Rozkład odpowiedzi na PYT_1 w Dziale Produktowym (PD)",
     "## Task 3 — PYT_1 response distribution in the Product Department (PD)"),
    ("## Zadanie 4 — Test Fishera: PŁEĆ vs CZY_KIER",
     "## Task 4 — Fisher test: GENDER vs CZY_KIER"),
    ("## Zadanie 5 — Test Freemana--Haltona",
     "## Task 5 — Freeman--Halton test"),
    ("## Zadanie 6 — Test $\\chi^2$ niezależności: PYT_2 vs CZY_KIER",
     "## Task 6 — $\\chi^2$ independence test: PYT_2 vs CZY_KIER"),
    ("## Zadanie 7 — Test niezależności oparty na ilorazie wiarogodności",
     "## Task 7 — Independence test based on the likelihood ratio"),
    ("## Zadanie 8 — Palenie a śmiertelność (rak płuc i choroba serca)",
     "## Task 8 — Smoking and mortality (lung cancer and heart disease)"),
    ("## Zadanie 9 — Współczynniki współzmienności (gamma, tau)",
     "## Task 9 — Association coefficients (gamma, tau)"),
    ('## Zadanie 10 — Analiza korespondencji "od zera"',
     '## Task 10 — Correspondence analysis "from scratch"'),
    ("## Zadanie *1 — Test oparty na korelacji odległości (dCor)",
     "## Task *1 — Distance correlation test (dCor)"),
    ("## Zadanie *2 — $|\\mathrm{RR} - 1| \\le |\\mathrm{OR} - 1|$ (RR bliżej 1 niż OR)",
     "## Task *2 — $|\\mathrm{RR} - 1| \\le |\\mathrm{OR} - 1|$ (RR closer to 1 than OR)"),
    ("## Zadanie *3 — Ryzyko przypisane (attributable risk)",
     "## Task *3 — Attributable risk"),
    ("# Zmienna CZY_ZADOW zdefiniowana w sprawozdaniu 1:",
     "# CZY_ZADOW variable defined in report 1:"),
    ("# pracownik zadowolony (Tak) gdy PYT_1 > 0, niezadowolony (Nie) w p.p.",
     "# employee satisfied (Tak) when PYT_1 > 0, dissatisfied (Nie) otherwise."),
    ("# Uporządkowane skale odpowiedzi (potrzebne do gamma/tau)",
     "# Ordered response scales (needed for gamma/tau)"),
    ("# Kategoryzacja wieku: 4 grupy", "# Age categorization: 4 groups"),
    ("# Wczytanie danych (CSV po konwersji do UTF-8, separator ';')",
     "# Load data (CSV in UTF-8, separator ';')"),
    ("# Test chi-kwadrat (Pearsona) i NW dla H0: p = p0",
     "# Pearson chi-square and LR test for H0: p = p0"),
    ('caption = "Przedziały ufności 95\\% dla p — metody Goodmana i Sison-Glaz."',
     'caption = "95\\% confidence intervals for p — Goodman and Sison-Glaz methods."'),
    ('caption = "Zaobserwowane liczności PYT\\_1 w dziale PD vs. oczekiwane przy równomierności."',
     'caption = "Observed PYT\\_1 counts in PD vs. expected under uniformity."'),
    ('caption = "Wyniki testów H0: rozkład PYT\\_1 w dziale PD jest równomierny."',
     'caption = "Test results for H0: PYT\\_1 distribution in PD is uniform."'),
    ('caption = "Tablica dwudzielcza PŁEĆ x CZY\\_KIER."',
     'caption = "Two-way table GENDER x CZY\\_KIER."'),
    ('caption = "Wyniki testów Freemana-Haltona (symulacja, B = 20000)."',
     'caption = "Freeman-Halton test results (simulation, B = 20000).'),
    ('caption = "Tablica dwudzielcza PYT\\_2 x CZY\\_KIER."',
     'caption = "Two-way table PYT\\_2 x CZY\\_KIER."'),
    ('caption = "Porównanie testu Pearsona i testu NW dla PYT\\_2 vs CZY\\_KIER."',
     'caption = "Comparison of Pearson and LR tests for PYT\\_2 vs CZY\\_KIER."'),
    ('caption = "Miary związku: palenie vs zgon z powodu raka płuc / choroby serca."',
     'caption = "Association measures: smoking vs death from lung cancer / heart disease."'),
    ('caption = "Goodman-Kruskal gamma i Kendall tau-b z 95\\% PU."',
     'caption = "Goodman-Kruskal gamma and Kendall tau-b with 95\\% CIs."'),
    ('plot_CA <- function(ca, main = "Analiza korespondencji")',
     'plot_CA <- function(ca, main = "Correspondence analysis")'),
    ('legend("topright", legend = c("wiersze (PYT_2)", "kolumny (STAŻ)")',
     'legend("topright", legend = c("rows (PYT_2)", "columns (TENURE)")'),
    ('caption = "Test niezależności oparty na dCor (999 permutacji)."',
     'caption = "Independence test based on dCor (999 permutations).'),
    ('caption = "Ilustracja: |OR-1| >= |RR-1|."',
     'caption = "Illustration: |OR-1| >= |RR-1|."'),
    ('Test         = c("chi-kwadrat Pearsona","chi-kwadrat NW")',
     'Test         = c("Pearson chi-square","LR chi-square")'),
    ('Test         = c("chi-kwadrat Pearsona (zad. 6)", "iloraz wiarogodności (NW)")',
     'Test         = c("Pearson chi-square (task 6)", "likelihood ratio (LR)")'),
    ('Decyzja     = ifelse(wyniki < 0.05, "odrzucić H0", "brak podstaw")',
     'Decyzja     = ifelse(wyniki < 0.05, "reject H0", "insufficient evidence")'),
    ('ifelse(ft$p.value < 0.05,"odrzucamy","nie mamy podstaw do odrzucenia")',
     'ifelse(ft$p.value < 0.05,"reject","we do not reject")'),
    ('ifelse(bt$p.value<0.05,"odrzucamy","nie mamy podstaw do odrzucenia")',
     'ifelse(bt$p.value<0.05,"reject","we do not reject")'),
    ('ifelse(chi6$p.value < 0.01,"odrzucamy","nie mamy podstaw do odrzucenia")',
     'ifelse(chi6$p.value < 0.01,"reject","we do not reject")'),
    ("**Jednoczesny przedział ufności na poziomie $1-\\alpha$** uzyskujemy dwiema",
     "**Simultaneous confidence interval at level $1-\\alpha$** is obtained by two"),
    ("klasycznymi metodami:", "classical methods:"),
    ("Funkcja zwraca wartość statystyki, stopnie swobody oraz asymptotyczną",
     "The function returns the statistic, degrees of freedom, and asymptotic"),
    ("p-wartość (a opcjonalnie dokładną Monte Carlo z ziarnem ustalonym globalnie).",
     "p-value (and optionally an exact Monte Carlo value with globally set seed)."),
]

REPORT3: list[tuple[str, str]] = [
    ('title: "Analiza Danych Ankietowych — Sprawozdanie 3"',
     'title: "Survey Data Analysis — Report 3"'),
    ("## Zadanie 1 — Warunkowy test symetrii dla tablicy $2\\times2$",
     "## Task 1 — Conditional symmetry test for a $2\\times2$ table"),
    ("## Zadanie 2 — Skuteczność dwóch leków przeciwbólowych",
     "## Task 2 — Efficacy of two analgesic drugs"),
    ("## Zadanie 3 — Symetria zadowolenia ze szkoleń w dwóch okresach",
     "## Task 3 — Symmetry of training satisfaction across two periods"),
    ("## Zadanie 4 — Symetria odpowiedzi (tablica $5\\times5$, test Bowkera)",
     "## Task 4 — Response symmetry ($5\\times5$ table, Bowker test)"),
    ("## Zadanie 5 — Paradoks Simpsona",
     "## Task 5 — Simpson's paradox"),
    ("## Zadanie 6 — Interpretacja modeli log-liniowych",
     "## Task 6 — Interpretation of log-linear models"),
    ("## Zadanie 7 — Estymacja prawdopodobieństw (modele $[123]$ i $[12\\ 23]$)",
     "## Task 7 — Probability estimation (models $[123]$ and $[12\\ 23]$)"),
    ("## Zadanie 8 — Weryfikacja hipotez niezależności (modele log-liniowe)",
     "## Task 8 — Testing independence hypotheses (log-linear models)"),
    ("## Zadanie 1\\* — Dokładny test symetrii dla tablicy z zerami",
     "## Task 1* — Exact symmetry test for a table with zeros"),
    ("# Wczytanie danych (CSV, separator ';', kodowanie UTF-8)",
     "# Load data (CSV, separator ';', UTF-8 encoding)"),
    ("# Zmienne pomocnicze wykorzystywane w kilku zadaniach",
     "# Helper variables used in several tasks"),
    ('# Zmienne "zadowolenia ze szkoleń" w dwóch okresach (zadanie 3).',
     '# "Training satisfaction" variables for two periods (task 3).'),
    ("# PYT_2 -> pierwszy okres, PYT_3 -> drugi okres; obie zmienne nie",
     "# PYT_2 -> first period, PYT_3 -> second period; neither variable"),
    ("# przyjmują wartości 0, więc binaryzacja względem zera jest jednoznaczna:",
     "# takes value 0, so binarization relative to zero is unambiguous:"),
    ('# odpowiedź dodatnia (1,2) = "Tak" (zadowolony), ujemna (-2,-1) = "Nie".',
     '# positive answer (1,2) = "Tak" (satisfied), negative (-2,-1) = "Nie".'),
    ("# Warunkowy (dokładny) test symetrii dla tablicy 2x2.",
     "# Conditional (exact) symmetry test for a 2x2 table."),
    ("# Zwraca dwustronną p-wartość opartą na rozkładzie Bin(m, 1/2).",
     "# Returns two-sided p-value based on Bin(m, 1/2) distribution."),
    ("# Bowker liczony ręcznie: pary z n_ij + n_ji = 0 są pomijane (0/0),",
     "# Bowker computed manually: pairs with n_ij + n_ji = 0 are skipped (0/0),"),
    ("# co zmniejsza efektywną liczbę stopni swobody.",
     "# which reduces the effective degrees of freedom."),
    ("# Model nasycony [123] = częstości empiryczne",
     "# Saturated model [123] = empirical frequencies"),
    ("# Model [12 23]: 1 i 3 warunkowo niezależne przy ustalonym 2",
     "# Model [12 23]: 1 and 3 conditionally independent given 2"),
    ('orf <- function(a, b, c, d) (a*d)/(b*c)   # iloraz szans (poprawa A:B)',
     'orf <- function(a, b, c, d) (a*d)/(b*c)   # odds ratio (improvement A:B)'),
    ('Test         = c("McNemar (z poprawką na ciągłość)", "warunkowy (zad. 1)")',
     'Test         = c("McNemar (with continuity correction)", "conditional (task 1)")'),
    ('Test        = c("McNemar (z poprawką na ciągłość)", "warunkowy (zad. 1)")',
     'Test        = c("McNemar (with continuity correction)", "conditional (task 1)")'),
    ('Wariant      = c("df nominalne = 10", "df efektywne = 9 (po usunięciu par 0/0)")',
     'Wariant      = c("nominal df = 10", "effective df = 9 (after removing 0/0 pairs)")'),
    ('caption = "Reakcja na lek A (wiersze) vs lek B (kolumny)."',
     'caption = "Response to drug A (rows) vs drug B (columns).'),
    ('caption = "Weryfikacja hipotezy o jednakowej skuteczności leków."',
     'caption = "Testing the hypothesis of equal drug efficacy."'),
    ('caption = "Zadowolenie ze szkoleń: okres 1 (wiersze) vs okres 2 (kolumny)."',
     'caption = "Training satisfaction: period 1 (rows) vs period 2 (columns).'),
    ('caption = "Test symetrii dla zadowolenia ze szkoleń."',
     'caption = "Symmetry test for training satisfaction."'),
    ('caption = "Odpowiedzi w okresie 1 (wiersze) vs okresie 2 (kolumny)."',
     'caption = "Responses in period 1 (rows) vs period 2 (columns).'),
    ('caption = "Test Bowkera symetrii dla tablicy 5×5."',
     'caption = "Bowker symmetry test for a 5×5 table."'),
    ('caption = "Liczba pacjentów z poprawą, odsetek poprawy i iloraz szans dla leczenia A vs B."',
     'caption = "Patients with improvement, improvement rate, and odds ratio for treatment A vs B."'),
    ('col.names = c("Model", "Postać $\\pi_{ijk}$", "Interpretacja")',
     'col.names = c("Model", "Form $\\pi_{ijk}$", "Interpretation")'),
    ('caption = "Interpretacja modeli log-liniowych (1 = CZY\\_KIER, 2 = PYT\\_2, 3 = STAŻ)."',
     'caption = "Interpretation of log-linear models (1 = CZY\\_KIER, 2 = PYT\\_2, 3 = TENURE).'),
    ('caption = "Oszacowania prawdopodobieństw w modelu nasyconym i [12 23]."',
     'caption = "Probability estimates in the saturated and [12 23] models."'),
    ('caption = "Testy ilorazu wiarogodności dla hipotez niezależności."',
     'caption = "Likelihood-ratio tests for independence hypotheses."'),
    ('Hipoteza = c("CZY_KIER, PYT_2, STAŻ wzajemnie niezależne"',
     'Hipoteza = c("CZY_KIER, PYT_2, TENURE mutually independent"'),
    ('"PYT_2 niezależna od pary (CZY_KIER, STAŻ)"',
     '"PYT_2 independent of the pair (CZY_KIER, TENURE)"'),
    ('"PYT_2 niezależna od CZY_KIER przy ustalonym STAŻ"',
     '"PYT_2 independent of CZY_KIER given TENURE"'),
    ('labs(x = "PYT_2 (odpowiedź)", y = "Liczba obserwacji")',
     'labs(x = "PYT_2 (response)", y = "Number of observations")'),
    ('labels = c("Nie kierownik", "Kierownik")',
     'labels = c("Non-manager", "Manager")'),
    ('dfp$Metoda <- ifelse(dfp$Metoda == "% popr. A", "Leczenie A", "Leczenie B")',
     'dfp$Metoda <- ifelse(dfp$Metoda == "% popr. A", "Treatment A", "Treatment B")'),
    ('scale_fill_manual(values = c("Leczenie A" = "steelblue", "Leczenie B" = "firebrick"))',
     'scale_fill_manual(values = c("Treatment A" = "steelblue", "Treatment B" = "firebrick"))'),
    ('```{r zad3-plot, fig.cap="Liczba pracowników zmieniających status zadowolenia między okresami. Komórki pozaprzekątniowe (Nie$\\\\to$Tak oraz Tak$\\\\to$Nie) decydują o teście symetrii."',
     '```{r zad3-plot, fig.cap="Number of employees changing satisfaction status between periods. Off-diagonal cells (Nie$\\\\to$Tak and Tak$\\\\to$Nie) determine the symmetry test."'),
    ('```{r zad8-plot, fig.height=5, fig.cap="Rozkład odpowiedzi PYT\\\\_2 w warstwach wyznaczonych przez staż (kolumny) oraz stanowisko kierownicze (wiersze). Każdy panel ma własną skalę osi pionowej (kierownicy są nieliczni)."',
     '```{r zad8-plot, fig.height=5, fig.cap="PYT\\\\_2 response distribution in strata by tenure (columns) and management role (rows). Each panel has its own y-axis scale (managers are few)."'),
    ('"\\\\textbf{Niezależność CZY\\\\_KIER i STAŻ} (model dla pary 1--3, z pominięciem zmiennej 2). Stanowisko nie zależy od stażu."',
     '"\\\\textbf{Independence of CZY\\\\_KIER and TENURE} (model for pair 1--3, omitting variable 2). Position does not depend on tenure."'),
    ('"\\\\textbf{Model nasycony dla pary 1--3} --- dopuszcza dowolną zależność (asocjację) między CZY\\\\_KIER a STAŻ."',
     '"\\\\textbf{Saturated model for pair 1--3} --- allows any association between CZY\\\\_KIER and TENURE."'),
    ('"\\\\textbf{Wzajemna (całkowita) niezależność} wszystkich trzech zmiennych."',
     '"\\\\textbf{Mutual (complete) independence} of all three variables."'),
    ('"\\\\textbf{STAŻ niezależny od pary (CZY\\\\_KIER, PYT\\\\_2)}; zmienne 1 i 2 mogą być powiązane."',
     '"\\\\textbf{TENURE independent of pair (CZY\\\\_KIER, PYT\\\\_2)}; variables 1 and 2 may be associated."'),
    ('"\\\\textbf{PYT\\\\_2 i STAŻ warunkowo niezależne przy ustalonym CZY\\\\_KIER} (zmienna 1 jest wspólnym rdzeniem)."',
     '"\\\\textbf{PYT\\\\_2 and TENURE conditionally independent given CZY\\\\_KIER} (variable 1 is the common core)."'),
    ('"\\\\textbf{CZY\\\\_KIER niezależny od pary (PYT\\\\_2, STAŻ)}; zmienne 2 i 3 mogą być powiązane."',
     '"\\\\textbf{CZY\\\\_KIER independent of pair (PYT\\\\_2, TENURE)}; variables 2 and 3 may be associated."'),
]

REPORT_MAP = {
    "sprawo1.qmd": REPORT1,
    "sprawozdanie2.qmd": REPORT2,
    "sprawozdanie3.qmd": REPORT3,
}

# Long prose paragraphs (applied after shorter replacements)
PROSE: list[tuple[str, str]] = [
    (
        "Celem niniejszego sprawozdania jest kompleksowa analiza wyników ankiety pracowniczej dotyczącej oceny programów szkoleniowych realizowanych przez firmę. Badanie zostało przeprowadzone wśród pracowników z różnych działów i szczebli organizacyjnych, co umożliwia wielowymiarową ocenę skuteczności polityki szkoleniowej.",
        "The purpose of this report is a comprehensive analysis of employee survey results evaluating training programs implemented by the company. The study was conducted among employees from different departments and organizational levels, enabling a multidimensional assessment of training policy effectiveness.",
    ),
    (
        "Raport jest kontynuacją sprawozdania 1 dotyczącego ankiety pracowniczej\n(n = 200, losowanie proste ze zwracaniem, cztery działy: IT, HR, MK, PD).\nZachowano konwencje zmiennych z poprzedniego sprawozdania, w szczególności\nzmienną binarną `CZY_ZADOW` (Tak, jeśli `PYT_1 > 0`) oraz zmienną\n`WIEK_KAT` kategoryzującą wiek do czterech grup:\n`do 35`, `36--45`, `46--55`, `powyżej 55`.",
        "This report continues report 1 on the employee survey\n(n = 200, simple random sampling with replacement, four departments: IT, HR, MK, PD).\nVariable conventions from the previous report are preserved, in particular\nthe binary variable `CZY_ZADOW` (Tak if `PYT_1 > 0`) and the\n`WIEK_KAT` variable categorizing age into four groups:\n`up to 35`, `36--45`, `46--55`, `over 55`.",
    ),
    (
        "Wszystkie obliczenia wykonano w R. Ziarno losowe ustawiono `set.seed(2025)`\n(dotyczy testów bazujących na symulacji, m.in. Freemana--Haltona).",
        "All computations were performed in R. The random seed was set to `set.seed(2025)`\n(for simulation-based tests, including Freeman--Halton).",
    ),
    (
        "Sprawozdanie dotyczy testów symetrii w tablicach kwadratowych, paradoksu\nSimpsona oraz modeli log-liniowych. Część obliczeń wykorzystuje dane z\npierwszej listy zadań (ankieta pracownicza, $n = 200$, działy IT, HR, MK,\nPD), część — dane podane bezpośrednio w treści zadań.",
        "This report covers symmetry tests in square tables, Simpson's paradox,\nand log-linear models. Some calculations use data from the first task list\n(employee survey, $n = 200$, departments IT, HR, MK, PD); others use\ndata given directly in the task statements.",
    ),
    (
        "Wszystkie obliczenia wykonano w R; ziarno losowe ustawiono na `set.seed(2025)`.",
        "All computations were performed in R; the random seed was set to `set.seed(2025)`.",
    ),
    (
        "Test ten jest dokładnym (warunkowym) odpowiednikiem testu McNemara; nie\nkorzysta z przybliżenia rozkładem $\\chi^2$, więc jest poprawny także przy\nmałych liczebnościach.",
        "This test is an exact (conditional) counterpart of McNemar's test; it does\nnot use a $\\chi^2$ approximation, so it remains valid for small counts.",
    ),
    (
        "**Odrzucamy** hipotezę symetrii. Oznacza to, że rozkład\nzadowolenia w dwóch okresach **nie** odpowiada modelowi symetrii — a zatem\n**poziom zadowolenia ze szkoleń uległ zmianie**. Kierunek przepływów\n(20 przejść na „Tak” wobec 8 na „Nie”) wskazuje na **wzrost** odsetka\nzadowolonych w drugim okresie.",
        "**We reject** the symmetry hypothesis. This means that the satisfaction\ndistribution across the two periods **does not** match a symmetry model — therefore\n**training satisfaction changed**. The direction of flows\n(20 transitions to \"Tak\" vs 8 to \"Nie\") indicates an **increase** in the proportion\nof satisfied employees in the second period.",
    ),
    (
        "**Tak, występuje paradoks Simpsona** — kierunek zależności\nodwraca się po uwzględnieniu zmiennej zakłócającej (choroby współistniejące).\nPrzyczyną jest nierównomierne rozłożenie ryzyka: metodę A częściej stosowano\nu trudniejszych pacjentów (choroby współistniejące miało 118 z 221 leczonych\nmetodą A wobec 38 z 221 leczonych metodą B), co pogorszyło jej zagregowany\nwynik. Właściwą oceną skuteczności jest analiza\nw podgrupach, która wskazuje na przewagę metody A.",
        "**Yes, Simpson's paradox occurs** — the direction of association\nreverses after accounting for a confounding variable (comorbidities).\nThe cause is uneven risk distribution: treatment A was used more often\nfor sicker patients (118 of 221 treated with A had comorbidities\nvs 38 of 221 treated with B), which worsened its aggregated\noutcome. The proper effectiveness assessment is subgroup\nanalysis, which indicates an advantage for treatment A.",
    ),
]

REPORT_SPECIFIC_PROSE = {
    "sprawo1.qmd": [
        (
            "Raport podzielono na trzy główne części. **Część I** obejmuje analizę opisową -- charakterystykę demograficzną i organizacyjną próby badawczej oraz rozkłady odpowiedzi na pytania ankietowe. **Część II** (nieuwzględniona w niniejszym sprawozdaniu) dotyczyłaby estymacji przedziałowej wskaźników zadowolenia z wykorzystaniem przedziałów ufności Cloppera-Pearsona. **Część III** poświęcona byłaby weryfikacji hipotez statystycznych dotyczących m.in. równości szans i skuteczności wprowadzonych działań.",
            "The report is divided into three main parts. **Part I** covers descriptive analysis — demographic and organizational characteristics of the sample and response distributions. **Part II** covers interval estimation of satisfaction indicators using Clopper-Pearson confidence intervals. **Part III** covers statistical hypothesis testing regarding equal opportunity and effectiveness of implemented measures.",
        ),
        (
            "Wyniki analizy mogą posłużyć jako podstawa do opracowania strategii doskonalenia systemu szkoleń, lepszego dopasowania oferty do potrzeb poszczególnych grup pracowników oraz oceny zwrotu z inwestycji w rozwój kadr.",
            "The analysis results can serve as a basis for developing a strategy to improve the training system, better tailoring offerings to employee groups, and evaluating return on investment in human capital development.",
        ),
        (
            "Pierwszym krokiem analizy jest import surowych danych z pliku `ankieta.csv` oraz ich transformacja do postaci odpowiedniej do analizy statystycznej. Plik zawiera odpowiedzi pracowników zebrane w ramach badania ankietowego.",
            "The first step is importing raw data from `ankieta.csv` and transforming it into a form suitable for statistical analysis. The file contains employee responses collected in the survey.",
        ),
        (
            "Zmienne jakościowe (dział, staż pracy, płeć, stanowisko, odpowiedzi na pytania) są przekształcane na **faktory** -- uporządkowane zmienne kategoryczne. Dzięki temu R poprawnie interpretuje ich hierarchię (np. skala Likerta od „Zdecydowanie nie zgadzam się\" do „Zdecydowanie zgadzam się\") i uwzględnia ją podczas tworzenia tabel oraz wykresów. Zmienna wiek jest przekształcana na typ numeryczny.",
            "Qualitative variables (department, tenure, gender, position, question responses) are converted to **factors** — ordered categorical variables. This lets R correctly interpret their hierarchy (e.g. Likert scale from \"Strongly disagree\" to \"Strongly agree\") when creating tables and plots. Age is converted to numeric type.",
        ),
        (
            "Po wczytaniu danych wyświetlamy poziomy każdego faktora oraz zakres zmiennej WIEK jako weryfikację poprawności wczytania:",
            "After loading data, we display each factor's levels and the WIEK range to verify correct import:",
        ),
    ],
}


def apply_replacements(text: str, pairs: list[tuple[str, str]]) -> str:
    """Apply replacements longest-first to reduce partial-match issues."""
    for old, new in sorted(pairs, key=lambda p: len(p[0]), reverse=True):
        text = text.replace(old, new)
    return text


def clean_header(text: str) -> str:
  """Remove empty lines left after stripping Polish LaTeX packages."""
  lines = []
  for line in text.splitlines():
    if line.strip() == "" and lines and lines[-1].strip() == "":
      continue
    lines.append(line)
  return "\n".join(lines)


def translate_file(src_name: str, dst_name: str) -> str:
    src = (ROOT / src_name).read_text(encoding="utf-8")
    # Full paragraphs first (keys must match Polish source text).
    prose_pairs = (
        PROSE
        + REPORT_SPECIFIC_PROSE.get(src_name, [])
        + PASS2
        + PASS2_R3
    )
    out = apply_replacements(src, prose_pairs)
    # Shorter phrase and structural replacements second.
    phrase_pairs = COMMON + REPORT_MAP.get(src_name, []) + FIXUPS
    out = apply_replacements(out, phrase_pairs)
    out = clean_header(out)
    (ROOT / dst_name).write_text(out, encoding="utf-8")
    return dst_name


def main() -> None:
    for src, dst in FILES.items():
        print(f"Translating {src} -> {dst}")
        translate_file(src, dst)
    print("Done.")


if __name__ == "__main__":
    main()

